"""Add cascade delete to ProgramWorkflowSteps for ApplicationWorkflowStatus

Revision ID: 7fa123a78a51
Revises: a1b39599a967
Create Date: 2026-02-10 02:38:24.096228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fa123a78a51'
down_revision = 'a1b39599a967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_workflow_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_workflow_history_application_id'))

    op.drop_table('application_workflow_history')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('use_income_range')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('use_beneficiary_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_beneficiary_limit', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('use_income_range', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('application_workflow_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_step_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('action_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('step_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], name=op.f('application_workflow_history_action_by_fkey')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('application_workflow_history_application_id_fkey')),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['program_workflow_steps.id'], name=op.f('application_workflow_history_workflow_step_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('application_workflow_history_pkey'))
    )
    with op.batch_alter_table('application_workflow_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_workflow_history_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###
