"""Initial migration

Revision ID: 936217dd0e15
Revises: 
Create Date: 2026-02-06 16:06:20.634229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936217dd0e15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_name', sa.String(length=255), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_requirement_type'), ['requirement_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('profile_complete_alert_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('mobile_no', sa.String(length=20), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('sitio', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('is_currently_employed', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('is_solo_parent', sa.Boolean(), nullable=True),
    sa.Column('is_pwd', sa.Boolean(), nullable=True),
    sa.Column('disability_type', sa.String(length=100), nullable=True),
    sa.Column('family_annual_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('senior_citizen_verification', sa.String(length=20), nullable=True),
    sa.Column('senior_citizen_id_number', sa.String(length=50), nullable=True),
    sa.Column('senior_citizen_verified_at', sa.DateTime(), nullable=True),
    sa.Column('senior_citizen_verified_by', sa.Integer(), nullable=True),
    sa.Column('senior_citizen_document_path', sa.String(length=255), nullable=True),
    sa.Column('senior_citizen_rejection_reason', sa.Text(), nullable=True),
    sa.Column('pwd_verification', sa.String(length=20), nullable=True),
    sa.Column('pwd_id_number', sa.String(length=50), nullable=True),
    sa.Column('pwd_verified_at', sa.DateTime(), nullable=True),
    sa.Column('pwd_verified_by', sa.Integer(), nullable=True),
    sa.Column('pwd_document_path', sa.String(length=255), nullable=True),
    sa.Column('pwd_rejection_reason', sa.Text(), nullable=True),
    sa.Column('solo_parent_verification', sa.String(length=20), nullable=True),
    sa.Column('solo_parent_id_number', sa.String(length=50), nullable=True),
    sa.Column('solo_parent_verified_at', sa.DateTime(), nullable=True),
    sa.Column('solo_parent_verified_by', sa.Integer(), nullable=True),
    sa.Column('solo_parent_document_path', sa.String(length=255), nullable=True),
    sa.Column('solo_parent_rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pwd_verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['senior_citizen_verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solo_parent_verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_users_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_barangay'), ['barangay'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_family_annual_income'), ['family_annual_income'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_is_currently_employed'), ['is_currently_employed'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_is_pwd'), ['is_pwd'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_is_solo_parent'), ['is_solo_parent'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_is_student'), ['is_student'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_pwd_verification'), ['pwd_verification'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_senior_citizen_verification'), ['senior_citizen_verification'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_solo_parent_verification'), ['solo_parent_verification'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_user_id'), ['user_id'], unique=False)

    op.create_table('file_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notif_title', sa.String(length=255), nullable=False),
    sa.Column('notif_message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(length=200), nullable=False),
    sa.Column('program_type', sa.String(length=50), nullable=False),
    sa.Column('program_period', sa.String(length=50), nullable=False),
    sa.Column('priority_group', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_limit', sa.Integer(), nullable=True),
    sa.Column('income_range', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_attachment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allow_online_upload', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_attachment_id'], ['file_attachment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_program_type'), ['program_type'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_title', sa.String(length=200), nullable=False),
    sa.Column('announcement_content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_created_at'), ['created_at'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('application_status', sa.String(length=20), nullable=False),
    sa.Column('document_upload_status', sa.String(length=20), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('claim_date', sa.DateTime(), nullable=True),
    sa.Column('claim_time', sa.String(length=10), nullable=True),
    sa.Column('claim_location', sa.String(length=255), nullable=True),
    sa.Column('claim_instructions', sa.Text(), nullable=True),
    sa.Column('claim_status', sa.String(length=20), nullable=True),
    sa.Column('claim_scheduled_by', sa.Integer(), nullable=True),
    sa.Column('claim_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('verification_code', sa.String(length=20), nullable=True),
    sa.Column('code_generated_at', sa.DateTime(), nullable=True),
    sa.Column('code_used_at', sa.DateTime(), nullable=True),
    sa.Column('documents_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_scheduled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('idx_app_program_status', ['program_id', 'application_status'], unique=False)
        batch_op.create_index('idx_app_user_date', ['user_id', 'application_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_application_date'), ['application_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_application_status'), ['application_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_claim_date'), ['claim_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_claim_status'), ['claim_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_document_upload_status'), ['document_upload_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_submission_deadline'), ['submission_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_verification_code'), ['verification_code'], unique=True)

    op.create_table('program_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('document_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('is_pre_approval', sa.Boolean(), nullable=True),
    sa.Column('requires_verification', sa.Boolean(), nullable=True),
    sa.Column('min_items', sa.Integer(), nullable=True),
    sa.Column('allowed_file_types', sa.String(length=255), nullable=True),
    sa.Column('step_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_document_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_document_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_document_uploads_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_document_uploads_verification_status'), ['verification_status'], unique=False)

    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('submission_status', sa.String(length=20), nullable=True),
    sa.Column('qualification_met', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_workflow_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step_id', sa.Integer(), nullable=False),
    sa.Column('step_status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('step_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['program_workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'workflow_step_id')
    )
    with op.batch_alter_table('application_workflow_status', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_status', ['application_id', 'step_status'], unique=False)

    op.create_table('cal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelter_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelter_photos')
    op.drop_table('cal_documents')
    with op.batch_alter_table('application_workflow_status', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_status')

    op.drop_table('application_workflow_status')
    op.drop_table('application_documents')
    with op.batch_alter_table('application_document_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_document_uploads_verification_status'))
        batch_op.drop_index(batch_op.f('ix_application_document_uploads_application_id'))

    op.drop_table('application_document_uploads')
    op.drop_table('announcement_images')
    op.drop_table('program_workflow_steps')
    op.drop_table('program_requirements')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_verification_code'))
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_submission_deadline'))
        batch_op.drop_index(batch_op.f('ix_applications_review_date'))
        batch_op.drop_index(batch_op.f('ix_applications_program_id'))
        batch_op.drop_index(batch_op.f('ix_applications_document_upload_status'))
        batch_op.drop_index(batch_op.f('ix_applications_claim_status'))
        batch_op.drop_index(batch_op.f('ix_applications_claim_date'))
        batch_op.drop_index(batch_op.f('ix_applications_application_status'))
        batch_op.drop_index(batch_op.f('ix_applications_application_date'))
        batch_op.drop_index('idx_app_user_date')
        batch_op.drop_index('idx_app_program_status')

    op.drop_table('applications')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_created_at'))

    op.drop_table('announcements')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_program_type'))
        batch_op.drop_index(batch_op.f('ix_programs_is_active'))

    op.drop_table('programs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    op.drop_table('file_attachment')
    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_users_solo_parent_verification'))
        batch_op.drop_index(batch_op.f('ix_community_users_senior_citizen_verification'))
        batch_op.drop_index(batch_op.f('ix_community_users_pwd_verification'))
        batch_op.drop_index(batch_op.f('ix_community_users_is_student'))
        batch_op.drop_index(batch_op.f('ix_community_users_is_solo_parent'))
        batch_op.drop_index(batch_op.f('ix_community_users_is_pwd'))
        batch_op.drop_index(batch_op.f('ix_community_users_is_currently_employed'))
        batch_op.drop_index(batch_op.f('ix_community_users_family_annual_income'))
        batch_op.drop_index(batch_op.f('ix_community_users_barangay'))
        batch_op.drop_index(batch_op.f('ix_community_users_age'))

    op.drop_table('community_users')
    op.drop_table('admin_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_requirement_type'))

    op.drop_table('requirements')
    # ### end Alembic commands ###
