"""Add workflow history tracking

Revision ID: a1b39599a967
Revises: a9e62b9b3f9d
Create Date: 2026-02-10 01:25:48.809296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b39599a967'
down_revision = 'a9e62b9b3f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_workflow_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=True),
    sa.Column('step_status', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('action_by', sa.Integer(), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('step_data', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['program_workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_workflow_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_workflow_history_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_workflow_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_workflow_history_application_id'))

    op.drop_table('application_workflow_history')
    # ### end Alembic commands ###
