"""Add toggle fields for beneficiary limit and income range

Revision ID: a9e62b9b3f9d
Revises: e7c37906bd77
Create Date: 2026-02-08 15:25:37.832571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e62b9b3f9d'
down_revision = 'e7c37906bd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_beneficiary_limit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('use_income_range', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('use_income_range')
        batch_op.drop_column('use_beneficiary_limit')

    # ### end Alembic commands ###
