"""Add profile fields (religion, place_of_birth, civil_status, highest_education_attainment) to community_users

Revision ID: add_profile_fields_community
Revises: add_areas_concern
Create Date: 2026-03-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_profile_fields_community'
down_revision = 'add_areas_concern'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('religion', sa.String(100), nullable=True))
        batch_op.add_column(sa.Column('place_of_birth', sa.String(200), nullable=True))
        batch_op.add_column(sa.Column('civil_status', sa.String(50), nullable=True))
        batch_op.add_column(sa.Column('highest_education_attainment', sa.String(100), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.drop_column('highest_education_attainment')
        batch_op.drop_column('civil_status')
        batch_op.drop_column('place_of_birth')
        batch_op.drop_column('religion')
