"""Add areas_of_concern to community_users table

Revision ID: add_areas_concern
Revises: update_test_users_income
Create Date: 2026-03-18 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_areas_concern'
down_revision = 'update_test_users_income'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('areas_of_concern', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.drop_column('areas_of_concern')
