"""Add_UserActivityLog_SavedProgram_HiddenProgram

Revision ID: c859c3ce65bc
Revises: e44da1ad8e91
Create Date: 2026-03-05 07:46:45.114001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c859c3ce65bc'
down_revision = 'e44da1ad8e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.create_index('idx_user_activity_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_user_activity_user_date', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('hidden_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_hidden_program')
    )
    op.create_table('saved_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_saved_program')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_programs')
    op.drop_table('hidden_programs')
    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_user_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_activity_logs_action_type'))
        batch_op.drop_index(batch_op.f('ix_user_activity_logs_action'))
        batch_op.drop_index('idx_user_activity_user_date')
        batch_op.drop_index('idx_user_activity_entity')

    op.drop_table('user_activity_logs')
    # ### end Alembic commands ###
