"""Add verification columns to community_users

Revision ID: e7c37906bd77
Revises: 936217dd0e15
Create Date: 2026-02-08 15:05:57.385390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c37906bd77'
down_revision = '936217dd0e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_workflow_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step_id', sa.Integer(), nullable=False),
    sa.Column('step_status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('step_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['program_workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'workflow_step_id')
    )
    with op.batch_alter_table('application_workflow_status', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_status', ['application_id', 'step_status'], unique=False)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_admin_users_user_id'))
        batch_op.drop_constraint(batch_op.f('admin_users_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('announcement_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_announcement_images_announcement_id'))
        batch_op.drop_index(batch_op.f('idx_announcement_images_display_order'))
        batch_op.drop_constraint(batch_op.f('announcement_images_announcement_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'announcements', ['announcement_id'], ['id'])

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_announcements_author_id'))
        batch_op.drop_index(batch_op.f('idx_announcements_category'))
        batch_op.drop_index(batch_op.f('idx_announcements_created_at'))
        batch_op.drop_index(batch_op.f('idx_announcements_program_id'))
        batch_op.drop_index(batch_op.f('idx_announcements_status'))
        batch_op.drop_index(batch_op.f('idx_announcements_status_created'))
        batch_op.create_index(batch_op.f('ix_announcements_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('announcements_program_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('announcements_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'])

    with op.batch_alter_table('application_document_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_doc_uploads_application_id'))
        batch_op.drop_index(batch_op.f('idx_doc_uploads_requirement_id'))
        batch_op.drop_index(batch_op.f('idx_doc_uploads_uploaded_at'))
        batch_op.drop_index(batch_op.f('idx_doc_uploads_verification_status'))
        batch_op.drop_index(batch_op.f('idx_doc_uploads_verified_by'))
        batch_op.create_index(batch_op.f('ix_application_document_uploads_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_document_uploads_verification_status'), ['verification_status'], unique=False)
        batch_op.drop_constraint(batch_op.f('application_document_uploads_verified_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('application_document_uploads_requirement_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('application_document_uploads_application_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])
        batch_op.create_foreign_key(None, 'requirements', ['requirement_id'], ['id'])

    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_application_documents_app_status'))
        batch_op.drop_index(batch_op.f('idx_application_documents_application_id'))
        batch_op.drop_index(batch_op.f('idx_application_documents_qualification_met'))
        batch_op.drop_index(batch_op.f('idx_application_documents_requirement_id'))
        batch_op.drop_index(batch_op.f('idx_application_documents_status'))
        batch_op.drop_index(batch_op.f('idx_application_documents_verified_by'))
        batch_op.drop_constraint(batch_op.f('application_documents_application_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('application_documents_requirement_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('application_documents_verified_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'requirements', ['requirement_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('applications_verification_code_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_app_status_date'))
        batch_op.drop_index(batch_op.f('idx_applications_claim_date'))
        batch_op.drop_index(batch_op.f('idx_applications_claim_scheduled_by'))
        batch_op.drop_index(batch_op.f('idx_applications_claim_status'))
        batch_op.drop_index(batch_op.f('idx_applications_date'))
        batch_op.drop_index(batch_op.f('idx_applications_document_upload_status'))
        batch_op.drop_index(batch_op.f('idx_applications_program_id'))
        batch_op.drop_index(batch_op.f('idx_applications_review_date'))
        batch_op.drop_index(batch_op.f('idx_applications_reviewed_by'))
        batch_op.drop_index(batch_op.f('idx_applications_status'))
        batch_op.drop_index(batch_op.f('idx_applications_submission_deadline'))
        batch_op.drop_index(batch_op.f('idx_applications_user_id'))
        batch_op.drop_index(batch_op.f('idx_applications_verification_code'))
        batch_op.create_index(batch_op.f('ix_applications_application_date'), ['application_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_application_status'), ['application_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_claim_date'), ['claim_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_claim_status'), ['claim_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_document_upload_status'), ['document_upload_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_submission_deadline'), ['submission_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_verification_code'), ['verification_code'], unique=True)
        batch_op.drop_constraint(batch_op.f('applications_claim_scheduled_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('applications_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('applications_program_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('applications_reviewed_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['claim_scheduled_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cal_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cal_documents_application_id'))
        batch_op.drop_index(batch_op.f('idx_cal_documents_document_type'))
        batch_op.drop_index(batch_op.f('idx_cal_documents_uploaded_at'))
        batch_op.drop_index(batch_op.f('idx_cal_documents_verification_status'))
        batch_op.drop_index(batch_op.f('idx_cal_documents_verified_by'))
        batch_op.drop_constraint(batch_op.f('cal_documents_verified_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cal_documents_application_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])

    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senior_citizen_verification', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('senior_citizen_id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('senior_citizen_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('senior_citizen_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('senior_citizen_document_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('senior_citizen_rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pwd_verification', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pwd_id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pwd_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pwd_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pwd_document_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pwd_rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('solo_parent_verification', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('solo_parent_id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('solo_parent_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('solo_parent_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('solo_parent_document_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('solo_parent_rejection_reason', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_community_age_employed'))
        batch_op.drop_index(batch_op.f('idx_community_barangay_income'))
        batch_op.drop_index(batch_op.f('idx_community_users_age'))
        batch_op.drop_index(batch_op.f('idx_community_users_barangay'))
        batch_op.drop_index(batch_op.f('idx_community_users_employed'))
        batch_op.drop_index(batch_op.f('idx_community_users_income'))
        batch_op.drop_index(batch_op.f('idx_community_users_solo_parent'))
        batch_op.drop_index(batch_op.f('idx_community_users_student'))
        batch_op.drop_index(batch_op.f('idx_community_users_user_id'))
        batch_op.create_index(batch_op.f('ix_community_users_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_barangay'), ['barangay'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_family_annual_income'), ['family_annual_income'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_is_currently_employed'), ['is_currently_employed'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_is_pwd'), ['is_pwd'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_is_solo_parent'), ['is_solo_parent'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_is_student'), ['is_student'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_pwd_verification'), ['pwd_verification'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_senior_citizen_verification'), ['senior_citizen_verification'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_solo_parent_verification'), ['solo_parent_verification'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_users_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('community_users_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['senior_citizen_verified_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['solo_parent_verified_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['pwd_verified_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('file_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_file_attachment_uploaded_at'))
        batch_op.drop_index(batch_op.f('idx_file_attachment_uploaded_by'))
        batch_op.drop_constraint(batch_op.f('file_attachment_uploaded_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_created_at'))
        batch_op.drop_index(batch_op.f('idx_notifications_is_read'))
        batch_op.drop_index(batch_op.f('idx_notifications_related_id'))
        batch_op.drop_index(batch_op.f('idx_notifications_related_type'))
        batch_op.drop_index(batch_op.f('idx_notifications_user_id'))
        batch_op.drop_index(batch_op.f('idx_notifications_user_read'))
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('program_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_program_requirements_mandatory'))
        batch_op.drop_index(batch_op.f('idx_program_requirements_program_id'))
        batch_op.drop_index(batch_op.f('idx_program_requirements_requirement_id'))
        batch_op.drop_constraint(batch_op.f('program_requirements_program_id_requirement_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('program_requirements_program_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('program_requirements_requirement_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'])
        batch_op.create_foreign_key(None, 'requirements', ['requirement_id'], ['id'])

    with op.batch_alter_table('program_workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_workflow_steps_order'))
        batch_op.drop_index(batch_op.f('idx_workflow_steps_program_id'))
        batch_op.drop_index(batch_op.f('idx_workflow_steps_type'))
        batch_op.drop_constraint(batch_op.f('program_workflow_steps_program_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'])

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_programs_date'))
        batch_op.drop_index(batch_op.f('idx_programs_file_attachment'))
        batch_op.drop_index(batch_op.f('idx_programs_is_active'))
        batch_op.drop_index(batch_op.f('idx_programs_period'))
        batch_op.drop_index(batch_op.f('idx_programs_type'))
        batch_op.drop_index(batch_op.f('idx_programs_type_active'))
        batch_op.drop_index(batch_op.f('idx_programs_user_id'))
        batch_op.create_index(batch_op.f('ix_programs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_program_type'), ['program_type'], unique=False)
        batch_op.drop_constraint(batch_op.f('programs_file_attachment_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('programs_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'file_attachment', ['file_attachment_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_requirements_created_at'))
        batch_op.drop_index(batch_op.f('idx_requirements_type'))
        batch_op.create_index(batch_op.f('ix_requirements_requirement_type'), ['requirement_type'], unique=False)

    with op.batch_alter_table('shelter_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shelter_photos_application_id'))
        batch_op.drop_index(batch_op.f('idx_shelter_photos_uploaded_at'))
        batch_op.drop_index(batch_op.f('idx_shelter_photos_verification_status'))
        batch_op.drop_index(batch_op.f('idx_shelter_photos_verified_by'))
        batch_op.drop_constraint(batch_op.f('shelter_photos_verified_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('shelter_photos_application_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_created_at'))
        batch_op.drop_index(batch_op.f('idx_user_email'))
        batch_op.drop_index(batch_op.f('idx_user_last_activity'))
        batch_op.drop_index(batch_op.f('idx_user_role'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_last_activity'), ['last_activity'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('shelter_photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('shelter_photos_application_id_fkey'), 'applications', ['application_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('shelter_photos_verified_by_fkey'), 'users', ['verified_by'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_shelter_photos_verified_by'), ['verified_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_shelter_photos_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_shelter_photos_uploaded_at'), [sa.literal_column('uploaded_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_shelter_photos_application_id'), ['application_id'], unique=False)

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_requirement_type'))
        batch_op.create_index(batch_op.f('idx_requirements_type'), ['requirement_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_requirements_created_at'), [sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('programs_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('programs_file_attachment_id_fkey'), 'file_attachment', ['file_attachment_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_programs_program_type'))
        batch_op.drop_index(batch_op.f('ix_programs_is_active'))
        batch_op.create_index(batch_op.f('idx_programs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_programs_type_active'), ['program_type', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_programs_type'), ['program_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_programs_period'), ['program_period'], unique=False)
        batch_op.create_index(batch_op.f('idx_programs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_programs_file_attachment'), ['file_attachment_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_programs_date'), [sa.literal_column('date DESC')], unique=False)

    with op.batch_alter_table('program_workflow_steps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('program_workflow_steps_program_id_fkey'), 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_workflow_steps_type'), ['step_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_workflow_steps_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_workflow_steps_order'), ['program_id', 'step_order'], unique=False)

    with op.batch_alter_table('program_requirements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('program_requirements_requirement_id_fkey'), 'requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('program_requirements_program_id_fkey'), 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('program_requirements_program_id_requirement_id_key'), ['program_id', 'requirement_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_program_requirements_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_program_requirements_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_program_requirements_mandatory'), ['is_mandatory'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.create_index(batch_op.f('idx_notifications_user_read'), ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_related_type'), ['related_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_related_id'), ['related_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_created_at'), [sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('file_attachment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('file_attachment_uploaded_by_id_fkey'), 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_file_attachment_uploaded_by'), ['uploaded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_file_attachment_uploaded_at'), [sa.literal_column('uploaded_at DESC')], unique=False)

    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('community_users_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_community_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_users_solo_parent_verification'))
        batch_op.drop_index(batch_op.f('ix_community_users_senior_citizen_verification'))
        batch_op.drop_index(batch_op.f('ix_community_users_pwd_verification'))
        batch_op.drop_index(batch_op.f('ix_community_users_is_student'))
        batch_op.drop_index(batch_op.f('ix_community_users_is_solo_parent'))
        batch_op.drop_index(batch_op.f('ix_community_users_is_pwd'))
        batch_op.drop_index(batch_op.f('ix_community_users_is_currently_employed'))
        batch_op.drop_index(batch_op.f('ix_community_users_family_annual_income'))
        batch_op.drop_index(batch_op.f('ix_community_users_barangay'))
        batch_op.drop_index(batch_op.f('ix_community_users_age'))
        batch_op.create_index(batch_op.f('idx_community_users_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_users_student'), ['is_student'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_users_solo_parent'), ['is_solo_parent'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_users_income'), ['family_annual_income'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_users_employed'), ['is_currently_employed'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_users_barangay'), ['barangay'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_users_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_barangay_income'), ['barangay', 'family_annual_income'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_age_employed'), ['age', 'is_currently_employed'], unique=False)
        batch_op.drop_column('solo_parent_rejection_reason')
        batch_op.drop_column('solo_parent_document_path')
        batch_op.drop_column('solo_parent_verified_by')
        batch_op.drop_column('solo_parent_verified_at')
        batch_op.drop_column('solo_parent_id_number')
        batch_op.drop_column('solo_parent_verification')
        batch_op.drop_column('pwd_rejection_reason')
        batch_op.drop_column('pwd_document_path')
        batch_op.drop_column('pwd_verified_by')
        batch_op.drop_column('pwd_verified_at')
        batch_op.drop_column('pwd_id_number')
        batch_op.drop_column('pwd_verification')
        batch_op.drop_column('senior_citizen_rejection_reason')
        batch_op.drop_column('senior_citizen_document_path')
        batch_op.drop_column('senior_citizen_verified_by')
        batch_op.drop_column('senior_citizen_verified_at')
        batch_op.drop_column('senior_citizen_id_number')
        batch_op.drop_column('senior_citizen_verification')

    with op.batch_alter_table('cal_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cal_documents_application_id_fkey'), 'applications', ['application_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('cal_documents_verified_by_fkey'), 'users', ['verified_by'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_cal_documents_verified_by'), ['verified_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_cal_documents_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_cal_documents_uploaded_at'), [sa.literal_column('uploaded_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_cal_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_cal_documents_application_id'), ['application_id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('applications_reviewed_by_fkey'), 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('applications_program_id_fkey'), 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('applications_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('applications_claim_scheduled_by_fkey'), 'users', ['claim_scheduled_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_applications_verification_code'))
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_submission_deadline'))
        batch_op.drop_index(batch_op.f('ix_applications_review_date'))
        batch_op.drop_index(batch_op.f('ix_applications_program_id'))
        batch_op.drop_index(batch_op.f('ix_applications_document_upload_status'))
        batch_op.drop_index(batch_op.f('ix_applications_claim_status'))
        batch_op.drop_index(batch_op.f('ix_applications_claim_date'))
        batch_op.drop_index(batch_op.f('ix_applications_application_status'))
        batch_op.drop_index(batch_op.f('ix_applications_application_date'))
        batch_op.create_index(batch_op.f('idx_applications_verification_code'), ['verification_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_submission_deadline'), ['submission_deadline'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_status'), ['application_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_document_upload_status'), ['document_upload_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_date'), [sa.literal_column('application_date DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_claim_status'), ['claim_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_claim_scheduled_by'), ['claim_scheduled_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_claim_date'), ['claim_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_app_status_date'), ['application_status', sa.literal_column('application_date DESC')], unique=False)
        batch_op.create_unique_constraint(batch_op.f('applications_verification_code_key'), ['verification_code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('application_documents_verified_by_fkey'), 'users', ['verified_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('application_documents_requirement_id_fkey'), 'requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('application_documents_application_id_fkey'), 'applications', ['application_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_application_documents_verified_by'), ['verified_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_application_documents_status'), ['submission_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_application_documents_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_application_documents_qualification_met'), ['qualification_met'], unique=False)
        batch_op.create_index(batch_op.f('idx_application_documents_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_application_documents_app_status'), ['application_id', 'submission_status'], unique=False)

    with op.batch_alter_table('application_document_uploads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('application_document_uploads_application_id_fkey'), 'applications', ['application_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('application_document_uploads_requirement_id_fkey'), 'requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('application_document_uploads_verified_by_fkey'), 'users', ['verified_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_application_document_uploads_verification_status'))
        batch_op.drop_index(batch_op.f('ix_application_document_uploads_application_id'))
        batch_op.create_index(batch_op.f('idx_doc_uploads_verified_by'), ['verified_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_doc_uploads_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_doc_uploads_uploaded_at'), [sa.literal_column('uploaded_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_doc_uploads_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_doc_uploads_application_id'), ['application_id'], unique=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('announcements_author_id_fkey'), 'users', ['author_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('announcements_program_id_fkey'), 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_announcements_created_at'))
        batch_op.create_index(batch_op.f('idx_announcements_status_created'), ['status', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_announcements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_announcements_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_announcements_created_at'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_announcements_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('idx_announcements_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('announcement_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('announcement_images_announcement_id_fkey'), 'announcements', ['announcement_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_announcement_images_display_order'), ['announcement_id', 'display_order'], unique=False)
        batch_op.create_index(batch_op.f('idx_announcement_images_announcement_id'), ['announcement_id'], unique=False)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_users_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_admin_users_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('application_workflow_status', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_status')

    op.drop_table('application_workflow_status')
    # ### end Alembic commands ###
